### ISSUE TITLE
网页版钱包有BUG

### ISSUE THREAD

**Issue by nxycdl** [gxchain/gxs-wallet#25]
当时9月4日的时候因为政策问题，我把一部分公信宝转到了公信宝的web钱包上了，最近想起来我把导入了备份的bin文件，密码也输入正确，提示我钱包导入成功。也能看到我的余额了。
![image](https://user-images.githubusercontent.com/6734755/35398545-22bf5938-022d-11e8-82a8-3d7273a2066d.png)
但无法转账， 显示 **不是你的账户 (提议)**  并且 只能看见公钥，点击公钥也不弹出私钥，
难道一定要用私钥导入才可以吗？ 网站不是写的是2选1个都可以吗？ 我既然钱包导入成功，为啥不让我看私钥，
另外我重新注册了一个钱包，清除浏览器之后按照同样的操作步骤， 在权限里面就能看到私钥？ 是因为我第一个账户建的太早有关系吗？

**Comment by nxycdl** [comment]
http://mp.weixin.qq.com/s/27v540tvhfDHF6Bv5_ObKQ  我是按照这个文档上面的第一个方法导入的。

**Comment by lanhaoxiang** [comment]
可以联系公信宝小秘书帮你解决，微信号：gxb-io3

**Comment by nxycdl** [comment]
@lanhaoxiang 这个微信一致都加不上啊。
