### ISSUE TITLE
gxs_wallet npm install err

### ISSUE THREAD

**Issue by gtrandxiangyu** [gxchain/gxs-wallet#26]
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 http://registry.cnpmjs.org/sntp
npm ERR! Error: ENOENT, lstat '/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/svg2png/node_modules/phantomjs-prebuilt/node_modules/request/node_modules/har-validator/node_modules/ajv/dist/regenerator.min.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/yangxing/work/gxc_wallet/gxs-wallet
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/svg2png/node_modules/phantomjs-prebuilt/node_modules/request/node_modules/har-validator/node_modules/ajv/dist/regenerator.min.js
npm ERR! fstream_path /home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/svg2png/node_modules/phantomjs-prebuilt/node_modules/request/node_modules/har-validator/node_modules/ajv/dist/regenerator.min.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http GET http://registry.cnpmjs.org/punycode
npm http GET http://registry.cnpmjs.org/extsprintf/1.3.0
npm http GET http://registry.cnpmjs.org/json-schema/0.2.3
npm http GET http://registry.cnpmjs.org/verror/1.10.0
npm http 304 http://registry.cnpmjs.org/hoek
npm http 304 http://registry.cnpmjs.org/boom
npm WARN engine cryptiles@3.1.2: wanted: {"node":">=4.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine sntp@2.1.0: wanted: {"node":">=4.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine hoek@4.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm WARN engine boom@4.3.1: wanted: {"node":">=4.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http 304 http://registry.cnpmjs.org/verror/1.10.0
npm WARN engine boom@5.2.0: wanted: {"node":">=4.0.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm http GET http://registry.cnpmjs.org/dom-walk
npm http 304 http://registry.cnpmjs.org/json-schema/0.2.3
npm http 304 http://registry.cnpmjs.org/extsprintf/1.3.0
npm http 304 http://registry.cnpmjs.org/punycode
npm http GET http://registry.cnpmjs.org/core-util-is/1.0.2
npm http GET http://registry.cnpmjs.org/asn1
npm http GET http://registry.cnpmjs.org/jsbn
npm http GET http://registry.cnpmjs.org/dashdash
npm http GET http://registry.cnpmjs.org/getpass
npm http 304 http://registry.cnpmjs.org/dom-walk
npm http GET http://registry.cnpmjs.org/ecc-jsbn
npm http GET http://registry.cnpmjs.org/tweetnacl
npm http GET http://registry.cnpmjs.org/bcrypt-pbkdf
npm ERR! Error: ENOENT, lstat '/home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/to-ico/node_modules/resize-img/node_modules/jpeg-js/test/fixtures/apsara.rgba'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-31-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/yangxing/work/gxc_wallet/gxs-wallet
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/to-ico/node_modules/resize-img/node_modules/jpeg-js/test/fixtures/apsara.rgba
npm ERR! fstream_path /home/yangxing/work/gxc_wallet/gxs-wallet/node_modules/favicons-webpack-plugin/node_modules/favicons/node_modules/to-ico/node_modules/resize-img/node_modules/jpeg-js/test/fixtures/apsara.rgba
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 http://registry.cnpmjs.org/core-util-is/1.0.2
npm http 304 http://registry.cnpmjs.org/getpass
npm http 304 http://registry.cnpmjs.org/jsbn
npm http 304 http://registry.cnpmjs.org/dashdash
npm http 304 http://registry.cnpmjs.org/tweetnacl
npm http 304 http://registry.cnpmjs.org/bcrypt-pbkdf
npm http 304 http://registry.cnpmjs.org/asn1
npm http 304 http://registry.cnpmjs.org/ecc-jsbn
npm http GET http://registry.cnpmjs.org/fast-deep-equal
npm http GET http://registry.cnpmjs.org/co
npm http GET http://registry.cnpmjs.org/fast-json-stable-stringify
npm http GET http://registry.cnpmjs.org/json-schema-traverse
npm http 304 http://registry.cnpmjs.org/fast-deep-equal
npm http 304 http://registry.cnpmjs.org/co
npm http 304 http://registry.cnpmjs.org/json-schema-traverse
npm http 304 http://registry.cnpmjs.org/fast-json-stable-stringify
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"v0.10.25","npm":"1.3.10"})
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/yangxing/work/gxc_wallet/gxs-wallet/npm-debug.log
npm ERR! not ok code 0
[npm-debug.log](https://github.com/gxchain/gxs-wallet/files/1710582/npm-debug.log)

**Comment by yrming** [comment]
更新一下你的node版本
