### ISSUE TITLE
全新下的代码，同时使用sudo，报告权限问题

### ISSUE THREAD

**Issue by gtrandxiangyu** [gxchain/gxs-wallet#28]
yangxing@ubuntu:~/work/gxc_wallet_new$ git clone https://github.com/gxchain/gxs-wallet.git
Cloning into 'gxs-wallet'...
remote: Counting objects: 1812, done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1812 (delta 0), reused 2 (delta 0), pack-reused 1802
Receiving objects: 100% (1812/1812), 12.19 MiB | 936.00 KiB/s, done.
Resolving deltas: 100% (1040/1040), done.
Checking connectivity... done.
yangxing@ubuntu:~/work/gxc_wallet_new$ cd gxs-wallet/
yangxing@ubuntu:~/work/gxc_wallet_new/gxs-wallet$ ls
build  config  package.json  README.md  src  static
yangxing@ubuntu:~/work/gxc_wallet_new/gxs-wallet$ sudo npm install
npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/bitshares/reconnecting-websocket.git /home/yangxing/.npm/_cacache/tmp/git-clone-e09b2e23
npm ERR! /home/yangxing/.npm/_cacache/tmp/git-clone-e09b2e23/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yangxing/.npm/_logs/2018-02-11T03_49_58_158Z-debug.log

**Comment by gtrandxiangyu** [comment]
2575 verbose stack Error: Command failed: /usr/bin/git clone -q https://github.com/bitshares/reconnecting-websocket.git /home/yangxing/.npm/_cacache/tmp/git-clone-e09b2e23
2575 verbose stack /home/yangxing/.npm/_cacache/tmp/git-clone-e09b2e23/.git: Permission denied
2575 verbose stack
2575 verbose stack     at ChildProcess.exithandler (child_process.js:272:12)
2575 verbose stack     at ChildProcess.emit (events.js:160:13)
2575 verbose stack     at maybeClose (internal/child_process.js:943:16)
2575 verbose stack     at Socket.stream.socket.on (internal/child_process.js:363:11)
2575 verbose stack     at Socket.emit (events.js:160:13)
2575 verbose stack     at Pipe._handle.close [as _onclose] (net.js:559:12)
2576 verbose cwd /home/yangxing/work/gxc_wallet_new/gxs-wallet
2577 verbose Linux 4.4.0-31-generic
2578 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
2579 verbose node v9.4.0
2580 verbose npm  v5.6.0
2581 error code 1
2582 error Command failed: /usr/bin/git clone -q https://github.com/bitshares/reconnecting-websocket.git /home/yangxing/.npm/_cacache/tmp/git-clone-e09b2e23
2582 error /home/yangxing/.npm/_cacache/tmp/git-clone-e09b2e23/.git: Permission denied
2583 verbose exit [ 1, true ]

**Comment by gtrandxiangyu** [comment]
已经使用sudo npm install了

**Comment by gtrandxiangyu** [comment]
@lanhaoxiang 大神，为啥把这个关闭了呀？这个怎么解决啊

**Comment by gtrandxiangyu** [comment]
@lanhaoxiang 大神，我是又全新下的代码，使用npm install，安装出现上述问题。增加了sudo也是有问题

**Comment by gtrandxiangyu** [comment]
yangxing@ubuntu:~/work/gxc_wallet/gxs-wallet$ node -v
v9.4.0
yangxing@ubuntu:~/work/gxc_wallet/gxs-wallet$ npm -v
5.6.0

┌────────────────────────────────────────────────────────────┐
│                  npm update check failed                   │
│            Try running with sudo or get access             │
│            to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) /home/yangxing/.config │
└────────────────────────────────────────────────────────────┘
yangxing@ubuntu:~/work/gxc_wallet/gxs-wallet$

**Comment by lanhaoxiang** [comment]
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.2/install.sh | bash
. ~/.nvm/nvm.sh
nvm install 6
nvm alias default 6
nvm use 6
npm config set registry https://registry.npm.taobao.org #国内用户推荐使用淘宝提供的镜像
```

**Comment by gtrandxiangyu** [comment]
yangxing@ubuntu:~/work/gxc_wallet_new/gxs-wallet$ npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! cb() never called!

**Comment by gtrandxiangyu** [comment]
如果使用 sudo npm install 则如下
yangxing@ubuntu:~/work/gxc_wallet_new/gxs-wallet$ sudo npm install
npm WARN deprecated babel-preset-es2015@6.24.1: ????  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! code 1
npm ERR! Command failed: /usr/bin/git clone -q https://github.com/bitshares/reconnecting-websocket.git /home/yangxing/.npm/_cacache/tmp/git-clone-4700fe88
npm ERR! /home/yangxing/.npm/_cacache/tmp/git-clone-4700fe88/.git: Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yangxing/.npm/_logs/2018-02-11T07_28_44_304Z-debug.log

**Comment by lanhaoxiang** [comment]
关注这个：  /home/yangxing/.npm/_cacache/tmp/git-clone-4700fe88/.git: Permission denied
