### ISSUE TITLE
npm start  Failed to compile with 4 errors  

### ISSUE THREAD

**Issue by gtrandxiangyu** [gxchain/gxs-wallet#29]
yangxing@ubuntu:~/work/gxc_wallet/gxs-wallet$ npm start

> gxb-mobile-wallet@1.0.0 start /home/yangxing/work/gxc_wallet/gxs-wallet
> node build/dev-server.js

isProd false
> Starting dev server...

 ERROR  Failed to compile with 4 errors                                                                                                                                                           11:17:26 PM

These dependencies were not found:

* @/components/WalletIndex in ./src/router/index.js
* @/components/WalletCreateStep1 in ./src/router/index.js
* @/components/WalletCreateStep2 in ./src/router/index.js

To install them, you can run: npm install --save @/components/WalletIndex @/components/WalletCreateStep1 @/components/WalletCreateStep2

This relative module was not found:

* ./components/sub/LoadingLayer in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
> Listening at http://localhost:8082

^C
yangxing@ubuntu:~/work/gxc_wallet/gxs-wallet$  npm install --save @/components/WalletIndex @/components/WalletCreateStep1 @/components/WalletCreateStep2
npm ERR! addLocal Could not install /home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex
npm ERR! addLocal Could not install /home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep1
npm ERR! addLocal Could not install /home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep2
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/home/yangxing/.nvm/versions/node/v6.12.3/bin/node" "/home/yangxing/.nvm/versions/node/v6.12.3/bin/npm" "install" "--save" "@/components/WalletIndex" "@/components/WalletCreateStep1" "@/components/WalletCreateStep2"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! path /home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex'
npm ERR! enoent ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/yangxing/work/gxc_wallet/gxs-wallet/npm-debug.log

**Comment by gtrandxiangyu** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/home/yangxing/.nvm/versions/node/v6.12.3/bin/node',
1 verbose cli   '/home/yangxing/.nvm/versions/node/v6.12.3/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   '@/components/WalletIndex',
1 verbose cli   '@/components/WalletCreateStep1',
1 verbose cli   '@/components/WalletCreateStep2' ]
2 info using npm@3.10.10
3 info using node@v6.12.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData @/components/WalletIndex
8 silly fetchPackageMetaData @/components/WalletCreateStep1
9 silly fetchPackageMetaData @/components/WalletCreateStep2
10 silly fetchOtherPackageData @/components/WalletIndex
11 silly cache add args [ '@/components/WalletIndex', null ]
12 verbose cache add spec @/components/WalletIndex
13 silly fetchOtherPackageData @/components/WalletCreateStep1
14 silly cache add args [ '@/components/WalletCreateStep1', null ]
15 verbose cache add spec @/components/WalletCreateStep1
16 silly fetchOtherPackageData @/components/WalletCreateStep2
17 silly cache add args [ '@/components/WalletCreateStep2', null ]
18 verbose cache add spec @/components/WalletCreateStep2
19 silly cache add parsed spec Result {
19 silly cache add   raw: '@/components/WalletIndex',
19 silly cache add   scope: null,
19 silly cache add   escapedName: null,
19 silly cache add   name: null,
19 silly cache add   rawSpec: '@/components/WalletIndex',
19 silly cache add   spec: '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex',
19 silly cache add   type: 'local' }
20 silly cache add parsed spec Result {
20 silly cache add   raw: '@/components/WalletCreateStep1',
20 silly cache add   scope: null,
20 silly cache add   escapedName: null,
20 silly cache add   name: null,
20 silly cache add   rawSpec: '@/components/WalletCreateStep1',
20 silly cache add   spec: '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep1',
20 silly cache add   type: 'local' }
21 silly cache add parsed spec Result {
21 silly cache add   raw: '@/components/WalletCreateStep2',
21 silly cache add   scope: null,
21 silly cache add   escapedName: null,
21 silly cache add   name: null,
21 silly cache add   rawSpec: '@/components/WalletCreateStep2',
21 silly cache add   spec: '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep2',
21 silly cache add   type: 'local' }
22 error addLocal Could not install /home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex
23 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex'
23 silly fetchPackageMetaData     at Error (native)
23 silly fetchPackageMetaData  error for @/components/WalletIndex { Error: ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex'
23 silly fetchPackageMetaData     at Error (native)
23 silly fetchPackageMetaData   errno: -2,
23 silly fetchPackageMetaData   code: 'ENOENT',
23 silly fetchPackageMetaData   syscall: 'open',
23 silly fetchPackageMetaData   path: '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex' }
24 error addLocal Could not install /home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep1
25 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep1'
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData  error for @/components/WalletCreateStep1 { Error: ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep1'
25 silly fetchPackageMetaData     at Error (native)
25 silly fetchPackageMetaData   errno: -2,
25 silly fetchPackageMetaData   code: 'ENOENT',
25 silly fetchPackageMetaData   syscall: 'open',
25 silly fetchPackageMetaData   path: '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep1' }
26 error addLocal Could not install /home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep2
27 silly fetchPackageMetaData Error: ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep2'
27 silly fetchPackageMetaData     at Error (native)
27 silly fetchPackageMetaData  error for @/components/WalletCreateStep2 { Error: ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep2'
27 silly fetchPackageMetaData     at Error (native)
27 silly fetchPackageMetaData   errno: -2,
27 silly fetchPackageMetaData   code: 'ENOENT',
27 silly fetchPackageMetaData   syscall: 'open',
27 silly fetchPackageMetaData   path: '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletCreateStep2' }
28 silly rollbackFailedOptional Starting
29 silly rollbackFailedOptional Finishing
30 silly runTopLevelLifecycles Finishing
31 silly install printInstalled
32 verbose stack Error: ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex'
32 verbose stack     at Error (native)
33 verbose cwd /home/yangxing/work/gxc_wallet/gxs-wallet
34 error Linux 4.4.0-31-generic
35 error argv "/home/yangxing/.nvm/versions/node/v6.12.3/bin/node" "/home/yangxing/.nvm/versions/node/v6.12.3/bin/npm" "install" "--save" "@/components/WalletIndex" "@/components/WalletCreateStep1" "@/components/WalletCreateStep2"
36 error node v6.12.3
37 error npm  v3.10.10
38 error path /home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex
39 error code ENOENT
40 error errno -2
41 error syscall open
42 error enoent ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex'
43 error enoent ENOENT: no such file or directory, open '/home/yangxing/work/gxc_wallet/gxs-wallet/@/components/WalletIndex'
43 error enoent This is most likely not a problem with npm itself
43 error enoent and is related to npm not being able to find a file.
44 verbose exit [ -2, true ]

**Comment by yrming** [comment]
rm -rf node_modules
npm install

**Comment by yrming** [comment]
npm install  最好是在科学上网环境下
