### ISSUE TITLE
ios版更新钱包打不开

### ISSUE THREAD

**Issue by cococardry** [gxchain/gxs-wallet#30]
手机型号：iphone X
问题：打开就显示“网络出错啦，请点击按钮重新加载”，点了也没用。

**Comment by lanhaoxiang** [comment]
去设置里面看下是否允许网络访问

**Comment by cococardry** [comment]
允许的，但是打不开
在2018年02月17日 23:48，Lan, Haoxiang 写道：

去设置里面看下是否允许网络访问

**Comment by lanhaoxiang** [comment]
麻烦提供以下系统版本号，还有允许网络访问的截图，尝试关闭后重新打开

**Comment by cococardry** [comment]
谢谢！
在2018年02月17日 23:57，Lan, Haoxiang 写道：

麻烦提供以下系统版本号，还有允许网络访问的截图，尝试关闭后重新打开
